export class StateService{
states = 
[
    { name: 'Alabama', value: 'AL' },
    { name: 'Alaska', value: 'AK' },
    { name: 'America Samoa', value: 'america samoa' },
    { name: 'Arizona', value: 'AZ' },
    { name: 'Arkansas', value: 'AR' },
    { name: 'California', value: 'CA' },
    { name: 'Colorado', value: 'CO' },
    { name: 'Connecticut', value: 'CN' },
    { name: 'Delaware', value: 'DE' },
    { name: 'District of Columbia', value: 'DC' },
    { name: 'Federated States of Micronesia', value: 'federated states of micronesia' },
    { name: 'Florida', value: 'FL' },
    { name: 'Georgia', value: 'GA' },
    { name: 'Guam', value: 'guam' },
    { name: 'Hawaii', value: 'HI' },
    { name: 'Idaho', value: 'ID' },
    { name: 'Illinois', value: 'IL' },
    { name: 'Indiana', value: 'ID' },
    { name: 'Iowa', value: 'IA' },
    { name: 'Kansas', value: 'kansas' },
    { name: 'Kentucky', value: 'kentucky' },
    { name: 'Louisiana', value: 'louisiana' },
    { name: 'Maine', value: 'maine' },
    { name: 'Marshall Islands', value: 'marshall islands' },
    { name: 'Maryland', value: 'maryland' },
    { name: 'Massachusetts', value: 'massachusetts' },
    { name: 'Michigan', value: 'michigan' },
    { name: 'Minnesota', value: 'minnesota' },
    { name: 'Mississippi', value: 'mississippi' },
    { name: 'Missouri', value: 'missouri' },
    { name: 'Montana', value: 'montana' },
    { name: 'Nebraska', value: 'nebraska' },
    { name: 'Nevada', value: 'nevada' },
    { name: 'New Hampshire', value: 'new hampshire' },
    { name: 'New Jersey', value: 'NJ' },
    { name: 'New Mexico', value: 'new mexico' },
    { name: 'New York', value: 'NY' },
    { name: 'North Carolina', value: 'north carolina' },
    { name: 'North Dakota', value: 'north dakota' },
    { name: 'Northern Mariana Islands', value: 'northern mariana islands' },
    { name: 'Ohio', value: 'ohio' },
    { name: 'Oklahoma', value: 'oklahoma' },
    { name: 'Oregon', value: 'oregon' },
    { name: 'Palau', value: 'palau' },
    { name: 'Pennsylvania', value: 'Pennsylvania' },
    { name: 'Puerto Rico', value: 'puerto rico' },
    { name: 'Rhode Island', value: 'rhode island' },
    { name: 'South Carolina', value: 'south carolina' },
    { name: 'South Dakota', value: 'south dakota' },
    { name: 'Tennesee', value: 'tennesee' },
    { name: 'Texas', value: 'texas' },
    { name: 'Utah', value: 'utah' },
    { name: 'Vermont', value: 'VT' },
    { name: 'Virgin Islands', value: 'virgin islands' },
    { name: 'Virginia', value: 'VI' },
    { name: 'Washington', value: 'WA' },
    { name: 'West Virginia', value: 'west virginia' },
    { name: 'Wisconsin', value: 'WI' },
    { name: 'Wyoming', value: 'WY' },
    { name: 'Sweden', value: 'sweden' },
    { name: 'Poland', value: 'poland' },
    { name: 'Bangladesh', value: 'bangladesh' },
    { name: 'Bulgaria', value: 'bulgaria' },
    { name: 'Netherlands', value: 'netherlands' },
    { name: 'Amsterdam', value: 'amsterdam' },
    { name: 'Austria', value: 'austria' },
    { name: 'Wales', value: 'wales' },
    { name: 'Japan', value: 'japan' },
  ];
  loadStates() {
    return new Promise((resolve, reject) => {
      resolve(this.states);
    });
  }
}